apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-spring-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: jenkins-spring-app-container
        image: safa318/jenkinsmyappspringboot-image:v1.0
        ports:
        - containerPort: 2222
