apiVersion: v1
kind: Service
metadata:
  name: jenkins-spring-app-service
spec:
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 2222 # Port exposé sur le service
    targetPort: 2222 # Port du conteneur
  type: NodePort
